import createContextHook from "@nkzw/create-context-hook";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useEffect, useState, useCallback, useMemo } from "react";

export type Language =
  | "fr"
  | "en"
  | "es"
  | "de"
  | "it"
  | "pt"
  | "ru"
  | "ar"
  | "id";

export type Translations = {
  home: string;
  shop: string;
  hive: string;
  alveole: string;
  menu: string;
  tasks: string;
  honey: string;
  flowers: string;
  diamonds: string;
  bees: string;
  honeyPerHour: string;
  honeyPerSec: string;
  faq: string;
  help: string;
  accountDetails: string;
  transactionHistory: string;
  loading: string;
  babyBee: string;
  workerBee: string;
  eliteBee: string;
  royalBee: string;
  queenBee: string;
  buy: string;
  exchange: string;
  withdraw: string;
  roulette: string;
  wallet: string;
  missions: string;
  invite: string;
  referrals: string;
  myReferralCode: string;
  inviteLink: string;
  friendsInvited: string;
  totalEarnings: string;
  myResources: string;
  buyFlowers: string;
  smallPack: string;
  mediumPack: string;
  largePack: string;
  giantPack: string;
  owned: string;
  statistics: string;
  totalProduction: string;
  totalBees: string;
  maxCapacity: string;
  close: string;
  chooseLanguage: string;
  spinTheWheel: string;
  withdrawCrypto: string;
  exchangeResources: string;
  receiveAndExchange: string;
  selectNetwork: string;
  walletAddress: string;
  withdrawAmount: string;
  summary: string;
  amount: string;
  fees: string;
  youWillReceive: string;
  importantInfo: string;
  error: string;
  success: string;
  confirmation: string;
  cancel: string;
  confirm: string;
  enterWalletAddress: string;
  enterValidAmount: string;
  notEnoughDiamonds: string;
  notEnoughBVR: string;
  withdrawalSubmitted: string;
  bvrWithdrawalSubmitted: string;
  availableBalance: string;
  network: string;
  minimumWithdraw: string;
  conversionRate: string;
  processingTime: string;
  verifyAddress: string;
  coldWalletRequired: string;
  inviteFriendBonus: string;
  copyReferralCode: string;
  copyInviteLink: string;
  copied: string;
  alreadyClaimed: string;
  missionIncomplete: string;
  rewardClaimed: string;
  referralBonus: string;
  perFriend: string;
  firstPurchaseBonus: string;
  firstDepositPercent: string;
  lifetimePercent: string;
  inviteFriends: string;
  progress: string;
  claim: string;
  claimed: string;
  inProgress: string;
  noReferrals: string;
  inviteToEarn: string;
  joinedOn: string;
  totalDeposits: string;
  firstDeposit: string;
  lifetimeEarnings: string;
  bvr: string;
  cryptoWithdraw: string;
  account: string;
  history: string;
  sellHoney: string;
  honeyExchange: string;
  honeyExchangeRate: string;
  quickSell: string;
  sellAllHoney: string;
  alveoleLevels: string;
  level: string;
  unlocked: string;
  capacity: string;
  cost: string;
  unlock: string;
  currentLevel: string;
  alveoleUnlocked: string;
  insufficientFlowers: string;
  needFlowers: string;
  insufficientHoney: string;
  needMinHoney: string;
  sold: string;
  transactionSuccess: string;
  transactionFailed: string;
  diamondExchangeRate: string;
  cryptoWithdrawPage: string;
  ticketsAvailable: string;
  spinning: string;
  noTickets: string;
  spinWheel: string;
  youWon: string;
  howToGetTickets: string;
  buyFlowersTicketInfo: string;
  exchangePage: string;
  yourBalances: string;
  exchangeType: string;
  diamondsToFlowers: string;
  bvrToFlowers: string;
  amountToExchange: string;
  exchangePreview: string;
  youGive: string;
  bonus: string;
  noFees: string;
  instant: string;
  walletPage: string;
  receiveAddresses: string;
  sendCryptoInfo: string;
  address: string;
  exchangeCrypto: string;
  afterSendingConfirm: string;
  networkLabel: string;
  amountSent: string;
  youWillReceiveFlowers: string;
  minimum: string;
  confirmExchange: string;
  important: string;
  verifyAddressWarning: string;
  cryptoIrreversible: string;
  useCorrectNetwork: string;
  minAmountWarning: string;
  exchangeAfterReceipt: string;
  exchangeQuestion: string;
  received: string;
  copied2: string;
  invalidAmount: string;
  selectNetworkError: string;
  selectExchangeType: string;
  minBVRError: string;
  onSolana: string;
  networkOnlyForBVR: string;
  minimum2: string;
  fillAllFields: string;
  passwordsDontMatch: string;
  passwordTooShort: string;
  createAccount: string;
  login: string;
  email: string;
  enterEmail: string;
  password: string;
  enterPassword: string;
  confirmPassword: string;
  confirmPasswordPlaceholder: string;
  sponsorCode: string;
  enterSponsorCode: string;
  register: string;
  loginButton: string;
  alreadyHaveAccount: string;
  dontHaveAccount: string;
  leaderboard: string;
  diamondLeaderboard: string;
  topProducers: string;
  you: string;
  joinBeeMinorPlayWin: string;
  forgotPassword: string;
  sendCode: string;
  resetPasswordTitle: string;
  resetButton: string;
  resetCode: string;
  enterResetCode: string;
  newPassword: string;
  enterNewPassword: string;
  confirmNewPassword: string;
  confirmYourNewPassword: string;
  backToLogin: string;
  emailSent: string;
  resetCodeSentTo: string;
  checkLogsForCode: string;
  passwordResetSuccess: string;
  canNowLogin: string;
  winChances: string;
  claimFailed: string;
};

const translations: Record<Language, Translations> = {
  fr: {
    home: "Accueil",
    shop: "Boutique",
    hive: "Ruche",
    alveole: "Alvéole",
    menu: "Menu",
    tasks: "Tâches",
    honey: "Miel",
    flowers: "Fleurs",
    diamonds: "Diamants",
    bees: "Abeilles",
    honeyPerHour: "Miel/Heure",
    honeyPerSec: "Miel/Sec",
    faq: "FAQ",
    help: "Aide",
    accountDetails: "Détail du compte",
    transactionHistory: "Historique",
    loading: "Chargement...",
    babyBee: "Abeille Bébé",
    workerBee: "Abeille",
    eliteBee: "Abeille Elite",
    royalBee: "Abeille Royal",
    queenBee: "Reine Abeille",
    buy: "Acheter",
    exchange: "Échanger",
    withdraw: "Retirer",
    roulette: "Roulette",
    wallet: "Portefeuille",
    missions: "Missions",
    invite: "Inviter",
    referrals: "Filleuls",
    myReferralCode: "Mon code de parrainage",
    inviteLink: "Lien d'invitation",
    friendsInvited: "Amis invités",
    totalEarnings: "Gains totaux",
    myResources: "Mes Ressources",
    buyFlowers: "Acheter des Fleurs",
    smallPack: "Pack Petit",
    mediumPack: "Pack Moyen",
    largePack: "Pack Grand",
    giantPack: "Pack Géant",
    owned: "Possédé",
    statistics: "Statistiques de Production",
    totalProduction: "Production totale",
    totalBees: "Nombre total d'abeilles",
    maxCapacity: "Capacité maximale",
    close: "Fermer",
    chooseLanguage: "Choisir la langue",
    spinTheWheel: "Tournez la roue pour gagner des prix",
    withdrawCrypto: "Retirez vos diamants en crypto",
    exchangeResources: "Échangez vos ressources contre des fleurs",
    receiveAndExchange: "Recevez des crypto et échangez contre des fleurs",
    selectNetwork: "Sélectionnez un réseau",
    walletAddress: "Adresse du portefeuille",
    withdrawAmount: "Montant du retrait",
    summary: "Résumé",
    amount: "Montant",
    fees: "Frais",
    youWillReceive: "Vous recevrez",
    importantInfo: "Informations importantes",
    error: "Erreur",
    success: "Succès",
    confirmation: "Confirmation",
    cancel: "Annuler",
    confirm: "Confirmer",
    enterWalletAddress: "Veuillez entrer une adresse de portefeuille",
    enterValidAmount: "Veuillez entrer un montant valide",
    notEnoughDiamonds: "Vous n'avez pas assez de diamants",
    notEnoughBVR: "Vous n'avez pas assez de BVR",
    withdrawalSubmitted:
      "Votre demande de retrait a été soumise. Vous recevrez vos fonds sous 24-48h.",
    bvrWithdrawalSubmitted:
      "Votre demande de retrait BVR a été soumise. Vous recevrez vos fonds sur Solana sous 24-48h.",
    availableBalance: "Solde disponible",
    network: "Réseau",
    minimumWithdraw: "Min",
    conversionRate: "Taux de conversion",
    processingTime: "Délai de traitement",
    verifyAddress: "Vérifiez bien votre adresse avant de confirmer",
    coldWalletRequired: "ATTENTION - Cold Wallet Obligatoire",
    inviteFriendBonus: "Inviter un ami",
    copyReferralCode: "Copié !",
    copyInviteLink: "Copier le lien d'invitation",
    copied: "Code de parrainage copié dans le presse-papiers",
    alreadyClaimed: "Vous avez déjà réclamé cette récompense",
    missionIncomplete: "Mission incomplète",
    rewardClaimed: "Récompense réclamée !",
    referralBonus: "Bonus de parrainage",
    perFriend: "par ami invité",
    firstPurchaseBonus: "si votre filleul fait un 1er achat",
    firstDepositPercent: "du montant du premier dépôt",
    lifetimePercent: "à vie sur tous les dépôts suivants",
    inviteFriends: "Inviter",
    progress: "Progrès",
    claim: "Réclamer",
    claimed: "Réclamé",
    inProgress: "En cours",
    noReferrals: "Aucun filleul pour le moment",
    inviteToEarn: "Invitez vos amis pour commencer à gagner des récompenses !",
    joinedOn: "Rejoint le",
    totalDeposits: "Dépôts totaux",
    firstDeposit: "Premier dépôt",
    lifetimeEarnings: "Gains à vie",
    bvr: "BVR",
    cryptoWithdraw: "Retrait Crypto",
    account: "Compte",
    history: "Historique",
    sellHoney: "Vendre du miel",
    honeyExchange: "Échange de miel",
    honeyExchangeRate: "1 miel (USDT) = 1 💎 diamant",
    quickSell: "Vente rapide",
    sellAllHoney: "Vendre tout le miel",
    alveoleLevels: "Niveaux d'Alvéoles",
    level: "Niveau",
    unlocked: "✓ Débloqué",
    capacity: "Capacité",
    cost: "Coût",
    unlock: "Débloquer",
    currentLevel: "Niveau actuel",
    alveoleUnlocked: "Alvéole niveau {level} débloqué!",
    insufficientFlowers: "Fleurs insuffisantes",
    needFlowers: "Vous avez besoin de {amount} fleurs.",
    insufficientHoney: "Miel insuffisant",
    needMinHoney: "Vous avez besoin d'au moins 1 miel (USDT) pour vendre.",
    sold: "Vendu!",
    transactionSuccess: "Transaction réussie!",
    transactionFailed: "Transaction échouée",
    diamondExchangeRate: "100 diamants = 0.01 fleurs",
    cryptoWithdrawPage: "Retrait Crypto",
    ticketsAvailable: "Tickets disponibles",
    spinning: "En rotation...",
    noTickets: "Pas de tickets",
    spinWheel: "TOURNER LA ROUE",
    youWon: "🎉 Vous avez gagné! 🎉",
    howToGetTickets: "Comment obtenir des tickets?",
    buyFlowersTicketInfo:
      "Achetez des fleurs dans la boutique! Chaque achat de 10$ vous donne 1 ticket.",
    exchangePage: "Échange",
    yourBalances: "Vos soldes",
    exchangeType: "Type d'échange",
    diamondsToFlowers: "Diamants vers Fleurs",
    bvrToFlowers: "BVR vers Fleurs",
    amountToExchange: "Montant à échanger",
    exchangePreview: "Aperçu de l'échange",
    youGive: "Vous donnez",
    bonus: "Bonus",
    noFees: "Aucuns frais",
    instant: "L'échange est instantané",
    walletPage: "Wallet",
    receiveAddresses: "Adresses de réception",
    sendCryptoInfo:
      "Envoyez des crypto à ces adresses pour recevoir des fleurs",
    address: "Adresse",
    exchangeCrypto: "Échanger des crypto",
    afterSendingConfirm:
      "Après avoir envoyé des crypto, confirmez l'échange ici",
    networkLabel: "Réseau",
    amountSent: "Montant envoyé",
    youWillReceiveFlowers: "Vous recevrez",
    minimum: "Minimum",
    confirmExchange: "Confirmer l'échange",
    important: "Important",
    verifyAddressWarning: "Vérifiez bien l'adresse avant d'envoyer",
    cryptoIrreversible: "Les transactions crypto sont irréversibles",
    useCorrectNetwork: "Utilisez le bon réseau (Solana ou TON)",
    minAmountWarning: "Montant minimum: 5$ (40,000 fleurs)",
    exchangeAfterReceipt:
      "L'échange se fait après réception de votre transaction",
    exchangeQuestion: "Échanger {amount} {currency} contre {flowers} fleurs ?",
    received: "Vous avez reçu {flowers} fleurs !",
    copied2: "Adresse copiée dans le presse-papier",
    invalidAmount: "Montant invalide",
    selectNetworkError: "Veuillez sélectionner un réseau",
    selectExchangeType: "Veuillez sélectionner un type d'échange",
    minBVRError: "Le montant minimum est de 100 BVR pour obtenir 0.01 fleur",
    onSolana: "sur Solana",
    networkOnlyForBVR: "Réseau unique pour les retraits BVR",
    minimum2: "Mín",
    fillAllFields: "Veuillez remplir tous les champs",
    passwordsDontMatch: "Les mots de passe ne correspondent pas",
    passwordTooShort: "Le mot de passe doit contenir au moins 6 caractères",
    createAccount: "Créer un compte",
    login: "Connexion",
    email: "Email",
    enterEmail: "Entrez votre email",
    password: "Mot de passe",
    enterPassword: "Entrez votre mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    confirmPasswordPlaceholder: "Confirmez votre mot de passe",
    sponsorCode: "Code parrain (optionnel)",
    enterSponsorCode: "Entrez le code parrain",
    register: "S'inscrire",
    loginButton: "Se connecter",
    alreadyHaveAccount: "Vous avez déjà un compte? Connectez-vous",
    dontHaveAccount: "Vous n'avez pas de compte? Inscrivez-vous",
    leaderboard: "Classement",
    diamondLeaderboard: "Classement Diamants",
    topProducers: "Top Producteurs Annuels",
    you: "Vous",
    joinBeeMinorPlayWin: "Rejoins les BeeMinor, joue et gagne",
    forgotPassword: "Mot de passe oublié?",
    sendCode: "Envoyer le code",
    resetPasswordTitle: "Réinitialiser le mot de passe",
    resetButton: "Réinitialiser",
    resetCode: "Code de réinitialisation",
    enterResetCode: "Entrez le code reçu par email",
    newPassword: "Nouveau mot de passe",
    enterNewPassword: "Entrez votre nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    confirmYourNewPassword: "Confirmez votre nouveau mot de passe",
    backToLogin: "Retour à la connexion",
    emailSent: "Email envoyé",
    resetCodeSentTo: "Un code de réinitialisation a été envoyé à",
    checkLogsForCode: "Vérifiez vos logs pour le code de test:",
    passwordResetSuccess:
      "Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter.",
    canNowLogin: "Vous pouvez maintenant vous connecter",
    winChances: "Chances de gagner",
    claimFailed: "Échec de la réclamation",
  },
  en: {
    home: "Home",
    shop: "Shop",
    hive: "Hive",
    alveole: "Alveole",
    menu: "Menu",
    tasks: "Tasks",
    honey: "Honey",
    flowers: "Flowers",
    diamonds: "Diamonds",
    bees: "Bees",
    honeyPerHour: "Honey/Hour",
    honeyPerSec: "Honey/Sec",
    faq: "FAQ",
    help: "Help",
    accountDetails: "Account Details",
    transactionHistory: "History",
    loading: "Loading...",
    babyBee: "Baby Bee",
    workerBee: "Worker Bee",
    eliteBee: "Elite Bee",
    royalBee: "Royal Bee",
    queenBee: "Queen Bee",
    buy: "Buy",
    exchange: "Exchange",
    withdraw: "Withdraw",
    roulette: "Roulette",
    wallet: "Wallet",
    missions: "Missions",
    invite: "Invite",
    referrals: "Referrals",
    myReferralCode: "My referral code",
    inviteLink: "Invite link",
    friendsInvited: "Friends invited",
    totalEarnings: "Total earnings",
    myResources: "My Resources",
    buyFlowers: "Buy Flowers",
    smallPack: "Small Pack",
    mediumPack: "Medium Pack",
    largePack: "Large Pack",
    giantPack: "Giant Pack",
    owned: "Owned",
    statistics: "Production Statistics",
    totalProduction: "Total production",
    totalBees: "Total number of bees",
    maxCapacity: "Max capacity",
    close: "Close",
    chooseLanguage: "Choose language",
    spinTheWheel: "Spin the wheel to win prizes",
    withdrawCrypto: "Withdraw your diamonds in crypto",
    exchangeResources: "Exchange your resources for flowers",
    receiveAndExchange: "Receive crypto and exchange for flowers",
    selectNetwork: "Select a network",
    walletAddress: "Wallet address",
    withdrawAmount: "Withdrawal amount",
    summary: "Summary",
    amount: "Amount",
    fees: "Fees",
    youWillReceive: "You will receive",
    importantInfo: "Important information",
    error: "Error",
    success: "Success",
    confirmation: "Confirmation",
    cancel: "Cancel",
    confirm: "Confirm",
    enterWalletAddress: "Please enter a wallet address",
    enterValidAmount: "Please enter a valid amount",
    notEnoughDiamonds: "You don't have enough diamonds",
    notEnoughBVR: "You don't have enough BVR",
    withdrawalSubmitted:
      "Your withdrawal request has been submitted. You will receive your funds within 24-48h.",
    bvrWithdrawalSubmitted:
      "Your BVR withdrawal request has been submitted. You will receive your funds on Solana within 24-48h.",
    availableBalance: "Available balance",
    network: "Network",
    minimumWithdraw: "Min",
    conversionRate: "Conversion rate",
    processingTime: "Processing time",
    verifyAddress: "Please verify your address before confirming",
    coldWalletRequired: "WARNING - Cold Wallet Required",
    inviteFriendBonus: "Invite a friend",
    copyReferralCode: "Copied!",
    copyInviteLink: "Copy invite link",
    copied: "Referral code copied to clipboard",
    alreadyClaimed: "You have already claimed this reward",
    missionIncomplete: "Mission incomplete",
    rewardClaimed: "Reward claimed!",
    referralBonus: "Referral bonus",
    perFriend: "per invited friend",
    firstPurchaseBonus: "if your referral makes a 1st purchase",
    firstDepositPercent: "of the first deposit amount",
    lifetimePercent: "lifetime on all following deposits",
    inviteFriends: "Invite",
    progress: "Progress",
    claim: "Claim",
    claimed: "Claimed",
    inProgress: "In progress",
    noReferrals: "No referrals yet",
    inviteToEarn: "Invite your friends to start earning rewards!",
    joinedOn: "Joined on",
    totalDeposits: "Total deposits",
    firstDeposit: "First deposit",
    lifetimeEarnings: "Lifetime earnings",
    bvr: "BVR",
    cryptoWithdraw: "Crypto Withdraw",
    account: "Account",
    history: "History",
    sellHoney: "Sell Honey",
    honeyExchange: "Honey Exchange",
    honeyExchangeRate:
      "1 miel (USDT) = 1 💎 diamond",
    quickSell: "Quick Sell",
    sellAllHoney: "Sell All Honey",
    alveoleLevels: "Alveole Levels",
    level: "Level",
    unlocked: "✓ Unlocked",
    capacity: "Capacity",
    cost: "Cost",
    unlock: "Unlock",
    currentLevel: "Current Level",
    alveoleUnlocked: "Alveole level {level} unlocked!",
    insufficientFlowers: "Insufficient flowers",
    needFlowers: "You need {amount} flowers.",
    insufficientHoney: "Insufficient honey",
    needMinHoney: "You need at least 100 honey to sell.",
    sold: "Sold!",
    transactionSuccess: "Transaction successful!",
    transactionFailed: "Transaction failed",
    diamondExchangeRate: "100 diamonds = 0.01 flowers",
    cryptoWithdrawPage: "Crypto Withdraw",
    ticketsAvailable: "Available tickets",
    spinning: "Spinning...",
    noTickets: "No tickets",
    spinWheel: "SPIN THE WHEEL",
    youWon: "🎉 You won! 🎉",
    howToGetTickets: "How to get tickets?",
    buyFlowersTicketInfo:
      "Buy flowers in the shop! Each $10 purchase gives you 1 ticket.",
    exchangePage: "Exchange",
    yourBalances: "Your balances",
    exchangeType: "Exchange type",
    diamondsToFlowers: "Diamonds to Flowers",
    bvrToFlowers: "BVR to Flowers",
    amountToExchange: "Amount to exchange",
    exchangePreview: "Exchange preview",
    youGive: "You give",
    bonus: "Bonus",
    noFees: "No fees",
    instant: "Exchange is instant",
    walletPage: "Wallet",
    receiveAddresses: "Receive addresses",
    sendCryptoInfo: "Send crypto to these addresses to receive flowers",
    address: "Address",
    exchangeCrypto: "Exchange crypto",
    afterSendingConfirm: "After sending crypto, confirm the exchange here",
    networkLabel: "Network",
    amountSent: "Amount sent",
    youWillReceiveFlowers: "You will receive",
    minimum: "Minimum",
    confirmExchange: "Confirm exchange",
    important: "Important",
    verifyAddressWarning: "Verify the address before sending",
    cryptoIrreversible: "Crypto transactions are irreversible",
    useCorrectNetwork: "Use the correct network (Solana or TON)",
    minAmountWarning: "Minimum amount: $5 (40,000 flowers)",
    exchangeAfterReceipt: "Exchange occurs after receiving your transaction",
    exchangeQuestion: "Exchange {amount} {currency} for {flowers} flowers?",
    received: "You received {flowers} flowers!",
    copied2: "Address copied to clipboard",
    invalidAmount: "Invalid amount",
    selectNetworkError: "Please select a network",
    selectExchangeType: "Please select an exchange type",
    minBVRError: "Minimum amount is 100 BVR to get 0.01 flower",
    onSolana: "on Solana",
    networkOnlyForBVR: "Only network for BVR withdrawals",
    minimum2: "Min",
    fillAllFields: "Please fill all fields",
    passwordsDontMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    createAccount: "Create Account",
    login: "Login",
    email: "Email",
    enterEmail: "Enter your email",
    password: "Password",
    enterPassword: "Enter your password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your password",
    sponsorCode: "Sponsor Code (optional)",
    enterSponsorCode: "Enter sponsor code",
    register: "Register",
    loginButton: "Log In",
    alreadyHaveAccount: "Already have an account? Log in",
    dontHaveAccount: "Don't have an account? Sign up",
    leaderboard: "Leaderboard",
    diamondLeaderboard: "Diamond Leaderboard",
    topProducers: "Top Annual Producers",
    you: "You",
    joinBeeMinorPlayWin: "Join BeeMinor, play and win",
    forgotPassword: "Forgot password?",
    sendCode: "Send code",
    resetPasswordTitle: "Reset password",
    resetButton: "Reset",
    resetCode: "Reset code",
    enterResetCode: "Enter the code received by email",
    newPassword: "New password",
    enterNewPassword: "Enter your new password",
    confirmNewPassword: "Confirm new password",
    confirmYourNewPassword: "Confirm your new password",
    backToLogin: "Back to login",
    emailSent: "Email sent",
    resetCodeSentTo: "A reset code has been sent to",
    checkLogsForCode: "Check your logs for the test code:",
    passwordResetSuccess:
      "Your password has been reset successfully. You can now log in.",
    canNowLogin: "You can now log in",
    winChances: "Win Chances",
    claimFailed: "Claim failed",
  },
  es: {
    home: "Inicio",
    shop: "Tienda",
    hive: "Colmena",
    alveole: "Alvéolo",
    menu: "Menú",
    tasks: "Tareas",
    honey: "Miel",
    flowers: "Flores",
    diamonds: "Diamantes",
    bees: "Abejas",
    honeyPerHour: "Miel/Hora",
    honeyPerSec: "Miel/Seg",
    faq: "FAQ",
    help: "Ayuda",
    accountDetails: "Detalles de cuenta",
    transactionHistory: "Historial",
    loading: "Cargando...",
    babyBee: "Abeja Bebé",
    workerBee: "Abeja Obrera",
    eliteBee: "Abeja Elite",
    royalBee: "Abeja Real",
    queenBee: "Abeja Reina",
    buy: "Comprar",
    exchange: "Intercambiar",
    withdraw: "Retirar",
    roulette: "Ruleta",
    wallet: "Cartera",
    missions: "Misiones",
    invite: "Invitar",
    referrals: "Referidos",
    myReferralCode: "Mi código de referido",
    inviteLink: "Enlace de invitación",
    friendsInvited: "Amigos invitados",
    totalEarnings: "Ganancias totales",
    myResources: "Mis Recursos",
    buyFlowers: "Comprar Flores",
    smallPack: "Pack Pequeño",
    mediumPack: "Pack Mediano",
    largePack: "Pack Grande",
    giantPack: "Pack Gigante",
    owned: "Poseído",
    statistics: "Estadísticas de Producción",
    totalProduction: "Producción total",
    totalBees: "Número total de abejas",
    maxCapacity: "Capacidad máxima",
    close: "Cerrar",
    chooseLanguage: "Elegir idioma",
    spinTheWheel: "Gira la ruleta para ganar premios",
    withdrawCrypto: "Retira tus diamantes en cripto",
    exchangeResources: "Intercambia tus recursos por flores",
    receiveAndExchange: "Recibe cripto e intercambia por flores",
    selectNetwork: "Selecciona una red",
    walletAddress: "Dirección de cartera",
    withdrawAmount: "Monto de retiro",
    summary: "Resumen",
    amount: "Monto",
    fees: "Comisiones",
    youWillReceive: "Recibirás",
    importantInfo: "Información importante",
    error: "Error",
    success: "Éxito",
    confirmation: "Confirmación",
    cancel: "Cancelar",
    confirm: "Confirmar",
    enterWalletAddress: "Por favor ingresa una dirección de cartera",
    enterValidAmount: "Por favor ingresa un monto válido",
    notEnoughDiamonds: "No tienes suficientes diamantes",
    notEnoughBVR: "No tienes suficientes BVR",
    withdrawalSubmitted:
      "Tu solicitud de retiro ha sido enviada. Recibirás tus fondos en 24-48h.",
    bvrWithdrawalSubmitted:
      "Tu solicitud de retiro BVR ha sido enviada. Recibirás tus fondos en Solana en 24-48h.",
    availableBalance: "Saldo disponible",
    network: "Red",
    minimumWithdraw: "Mín",
    conversionRate: "Tasa de conversión",
    processingTime: "Tiempo de procesamiento",
    verifyAddress: "Verifica bien tu dirección antes de confirmar",
    coldWalletRequired: "ATENCIÓN - Cold Wallet Obligatoria",
    inviteFriendBonus: "Invitar un amigo",
    copyReferralCode: "¡Copiado!",
    copyInviteLink: "Copiar enlace de invitación",
    copied: "Código de referido copiado al portapapeles",
    alreadyClaimed: "Ya has reclamado esta recompensa",
    missionIncomplete: "Misión incompleta",
    rewardClaimed: "¡Recompensa reclamada!",
    referralBonus: "Bono de referido",
    perFriend: "por amigo invitado",
    firstPurchaseBonus: "si tu referido hace una 1ra compra",
    firstDepositPercent: "del monto del primer depósito",
    lifetimePercent: "de por vida en todos los depósitos siguientes",
    inviteFriends: "Invitar",
    progress: "Progreso",
    claim: "Reclamar",
    claimed: "Reclamado",
    inProgress: "En progreso",
    noReferrals: "No hay referidos aún",
    inviteToEarn: "¡Invita a tus amigos para empezar a ganar recompensas!",
    joinedOn: "Se unió el",
    totalDeposits: "Depósitos totales",
    firstDeposit: "Primer depósito",
    lifetimeEarnings: "Ganancias de por vida",
    bvr: "BVR",
    cryptoWithdraw: "Retiro Cripto",
    account: "Cuenta",
    history: "Historial",
    sellHoney: "Vender miel",
    honeyExchange: "Intercambio de miel",
    honeyExchangeRate: "1 miel (USDT) = 1 💎 diamante",
    quickSell: "Venta rápida",
    sellAllHoney: "Vender toda la miel",
    alveoleLevels: "Niveles de Alvéolos",
    level: "Nivel",
    unlocked: "✓ Desbloqueado",
    capacity: "Capacidad",
    cost: "Costo",
    unlock: "Desbloquear",
    currentLevel: "Nivel actual",
    alveoleUnlocked: "¡Alvéolo nivel {level} desbloqueado!",
    insufficientFlowers: "Flores insuficientes",
    needFlowers: "Necesitas {amount} flores.",
    insufficientHoney: "Miel insuficiente",
    needMinHoney: "Necesitas al menos 100 miel para vender.",
    sold: "¡Vendido!",
    transactionSuccess: "¡Transacción exitosa!",
    transactionFailed: "Transacción fallida",
    diamondExchangeRate: "100 diamantes = 0.01 flores",
    cryptoWithdrawPage: "Retiro Cripto",
    ticketsAvailable: "Tickets disponibles",
    spinning: "Girando...",
    noTickets: "Sin tickets",
    spinWheel: "GIRAR LA RULETA",
    youWon: "🎉 ¡Ganaste! 🎉",
    howToGetTickets: "¿Cómo obtener tickets?",
    buyFlowersTicketInfo:
      "¡Compra flores en la tienda! Cada compra de $10 te da 1 ticket.",
    exchangePage: "Intercambio",
    yourBalances: "Tus saldos",
    exchangeType: "Tipo de intercambio",
    diamondsToFlowers: "Diamantes a Flores",
    bvrToFlowers: "BVR a Flores",
    amountToExchange: "Monto a intercambiar",
    exchangePreview: "Vista previa del intercambio",
    youGive: "Das",
    bonus: "Bono",
    noFees: "Sin comisiones",
    instant: "El intercambio es instantáneo",
    walletPage: "Cartera",
    receiveAddresses: "Direcciones de recepción",
    sendCryptoInfo: "Envía cripto a estas direcciones para recibir flores",
    address: "Dirección",
    exchangeCrypto: "Intercambiar cripto",
    afterSendingConfirm:
      "Después de enviar cripto, confirma el intercambio aquí",
    networkLabel: "Red",
    amountSent: "Monto enviado",
    youWillReceiveFlowers: "Recibirás",
    minimum: "Mínimo",
    confirmExchange: "Confirmar intercambio",
    important: "Importante",
    verifyAddressWarning: "Verifica la dirección antes de enviar",
    cryptoIrreversible: "Las transacciones cripto son irreversibles",
    useCorrectNetwork: "Usa la red correcta (Solana o TON)",
    minAmountWarning: "Monto mínimo: $5 (40,000 flores)",
    exchangeAfterReceipt:
      "El intercambio se realiza después de recibir tu transacción",
    exchangeQuestion: "¿Intercambiar {amount} {currency} por {flowers} flores?",
    received: "¡Recibiste {flowers} flores!",
    copied2: "Dirección copiada al portapapeles",
    invalidAmount: "Monto inválido",
    selectNetworkError: "Por favor selecciona una red",
    selectExchangeType: "Por favor selecciona un tipo de intercambio",
    minBVRError: "El monto mínimo es de 100 BVR para obtener 0.01 flor",
    onSolana: "en Solana",
    networkOnlyForBVR: "Red única para retiros BVR",
    minimum2: "Mín",
    fillAllFields: "Por favor complete todos los campos",
    passwordsDontMatch: "Las contraseñas no coinciden",
    passwordTooShort: "La contraseña debe tener al menos 6 caracteres",
    createAccount: "Crear Cuenta",
    login: "Iniciar Sesión",
    email: "Email",
    enterEmail: "Ingrese su email",
    password: "Contraseña",
    enterPassword: "Ingrese su contraseña",
    confirmPassword: "Confirmar Contraseña",
    confirmPasswordPlaceholder: "Confirme su contraseña",
    sponsorCode: "Código de patrocinador (opcional)",
    enterSponsorCode: "Ingrese código de patrocinador",
    register: "Registrarse",
    loginButton: "Iniciar Sesión",
    alreadyHaveAccount: "¿Ya tienes una cuenta? Inicia sesión",
    dontHaveAccount: "¿No tienes una cuenta? Regístrate",
    leaderboard: "Clasificación",
    diamondLeaderboard: "Clasificación de Diamantes",
    topProducers: "Mejores Productores Anuales",
    you: "Tú",
    joinBeeMinorPlayWin: "Únete a BeeMinor, juega y gana",
    forgotPassword: "¿Olvidaste tu contraseña?",
    sendCode: "Enviar código",
    resetPasswordTitle: "Restablecer contraseña",
    resetButton: "Restablecer",
    resetCode: "Código de restablecimiento",
    enterResetCode: "Ingresa el código recibido por email",
    newPassword: "Nueva contraseña",
    enterNewPassword: "Ingresa tu nueva contraseña",
    confirmNewPassword: "Confirmar nueva contraseña",
    confirmYourNewPassword: "Confirma tu nueva contraseña",
    backToLogin: "Volver al inicio de sesión",
    emailSent: "Email enviado",
    resetCodeSentTo: "Se ha enviado un código de restablecimiento a",
    checkLogsForCode: "Revisa tus logs para el código de prueba:",
    passwordResetSuccess:
      "Tu contraseña ha sido restablecida con éxito. Ahora puedes iniciar sesión.",
    canNowLogin: "Ahora puedes iniciar sesión",
    winChances: "Probabilidades de ganar",
    claimFailed: "Fallo al reclamar",
  },
  de: {
    home: "Startseite",
    shop: "Laden",
    hive: "Bienenstock",
    alveole: "Wabe",
    menu: "Menü",
    tasks: "Aufgaben",
    honey: "Honig",
    flowers: "Blumen",
    diamonds: "Diamanten",
    bees: "Bienen",
    honeyPerHour: "Honig/Stunde",
    honeyPerSec: "Honig/Sek",
    faq: "FAQ",
    help: "Hilfe",
    accountDetails: "Kontodetails",
    transactionHistory: "Verlauf",
    loading: "Wird geladen...",
    babyBee: "Baby-Biene",
    workerBee: "Arbeiterbiene",
    eliteBee: "Elite-Biene",
    royalBee: "Königliche Biene",
    queenBee: "Bienenkönigin",
    buy: "Kaufen",
    exchange: "Tauschen",
    withdraw: "Abheben",
    roulette: "Roulette",
    wallet: "Geldbörse",
    missions: "Missionen",
    invite: "Einladen",
    referrals: "Empfehlungen",
    myReferralCode: "Mein Empfehlungscode",
    inviteLink: "Einladungslink",
    friendsInvited: "Eingeladene Freunde",
    totalEarnings: "Gesamteinnahmen",
    myResources: "Meine Ressourcen",
    buyFlowers: "Blumen kaufen",
    smallPack: "Kleines Paket",
    mediumPack: "Mittleres Paket",
    largePack: "Großes Paket",
    giantPack: "Riesiges Paket",
    owned: "Besitz",
    statistics: "Produktionsstatistiken",
    totalProduction: "Gesamtproduktion",
    totalBees: "Gesamtzahl der Bienen",
    maxCapacity: "Maximale Kapazität",
    close: "Schließen",
    chooseLanguage: "Sprache wählen",
    spinTheWheel: "Drehen Sie das Rad, um Preise zu gewinnen",
    withdrawCrypto: "Ziehen Sie Ihre Diamanten in Krypto ab",
    exchangeResources: "Tauschen Sie Ihre Ressourcen gegen Blumen",
    receiveAndExchange: "Krypto erhalten und gegen Blumen tauschen",
    selectNetwork: "Wählen Sie ein Netzwerk",
    walletAddress: "Wallet-Adresse",
    withdrawAmount: "Auszahlungsbetrag",
    summary: "Zusammenfassung",
    amount: "Betrag",
    fees: "Gebühren",
    youWillReceive: "Sie erhalten",
    importantInfo: "Wichtige Informationen",
    error: "Fehler",
    success: "Erfolg",
    confirmation: "Bestätigung",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    enterWalletAddress: "Bitte geben Sie eine Wallet-Adresse ein",
    enterValidAmount: "Bitte geben Sie einen gültigen Betrag ein",
    notEnoughDiamonds: "Sie haben nicht genug Diamanten",
    notEnoughBVR: "Sie haben nicht genug BVR",
    withdrawalSubmitted:
      "Ihre Auszahlungsanfrage wurde eingereicht. Sie erhalten Ihr Geld innerhalb von 24-48h.",
    bvrWithdrawalSubmitted:
      "Ihre BVR-Auszahlungsanfrage wurde eingereicht. Sie erhalten Ihr Geld auf Solana innerhalb von 24-48h.",
    availableBalance: "Verfügbares Guthaben",
    network: "Netzwerk",
    minimumWithdraw: "Min",
    conversionRate: "Umrechnungskurs",
    processingTime: "Bearbeitungszeit",
    verifyAddress: "Bitte überprüfen Sie Ihre Adresse vor der Bestätigung",
    coldWalletRequired: "ACHTUNG - Cold Wallet erforderlich",
    inviteFriendBonus: "Einen Freund einladen",
    copyReferralCode: "Kopiert!",
    copyInviteLink: "Einladungslink kopieren",
    copied: "Empfehlungscode in die Zwischenablage kopiert",
    alreadyClaimed: "Sie haben diese Belohnung bereits beansprucht",
    missionIncomplete: "Mission unvollständig",
    rewardClaimed: "Belohnung beansprucht!",
    referralBonus: "Empfehlungsbonus",
    perFriend: "pro eingeladenem Freund",
    firstPurchaseBonus: "wenn Ihre Empfehlung einen 1. Kauf tätigt",
    firstDepositPercent: "des ersten Einzahlungsbetrags",
    lifetimePercent: "lebenslang auf alle folgenden Einzahlungen",
    inviteFriends: "Einladen",
    progress: "Fortschritt",
    claim: "Beanspruchen",
    claimed: "Beansprucht",
    inProgress: "In Bearbeitung",
    noReferrals: "Noch keine Empfehlungen",
    inviteToEarn: "Laden Sie Ihre Freunde ein, um Belohnungen zu verdienen!",
    joinedOn: "Beigetreten am",
    totalDeposits: "Gesamteinzahlungen",
    firstDeposit: "Erste Einzahlung",
    lifetimeEarnings: "Lebenslange Einnahmen",
    bvr: "BVR",
    cryptoWithdraw: "Krypto-Auszahlung",
    account: "Konto",
    history: "Verlauf",
    sellHoney: "Honig verkaufen",
    honeyExchange: "Honig-Tausch",
    honeyExchangeRate: "1 miel (USDT) = 1 💎 Diamant",
    quickSell: "Schnellverkauf",
    sellAllHoney: "Ganzen Honig verkaufen",
    alveoleLevels: "Waben-Stufen",
    level: "Stufe",
    unlocked: "✓ Freigeschaltet",
    capacity: "Kapazität",
    cost: "Kosten",
    unlock: "Freischalten",
    currentLevel: "Aktuelle Stufe",
    alveoleUnlocked: "Wabe Stufe {level} freigeschaltet!",
    insufficientFlowers: "Nicht genug Blumen",
    needFlowers: "Sie benötigen {amount} Blumen.",
    insufficientHoney: "Nicht genug Honig",
    needMinHoney: "Sie benötigen mindestens 100 Honig zum Verkaufen.",
    sold: "Verkauft!",
    transactionSuccess: "Transaktion erfolgreich!",
    transactionFailed: "Transaktion fehlgeschlagen",
    diamondExchangeRate: "100 Diamanten = 0.01 Blumen",
    cryptoWithdrawPage: "Krypto-Auszahlung",
    ticketsAvailable: "Verfügbare Tickets",
    spinning: "Dreht sich...",
    noTickets: "Keine Tickets",
    spinWheel: "RAD DREHEN",
    youWon: "🎉 Sie haben gewonnen! 🎉",
    howToGetTickets: "Wie bekommt man Tickets?",
    buyFlowersTicketInfo:
      "Kaufen Sie Blumen im Laden! Jeder 10$ Kauf gibt Ihnen 1 Ticket.",
    exchangePage: "Tausch",
    yourBalances: "Ihre Guthaben",
    exchangeType: "Tauschtyp",
    diamondsToFlowers: "Diamanten zu Blumen",
    bvrToFlowers: "BVR zu Blumen",
    amountToExchange: "Zu tauschender Betrag",
    exchangePreview: "Tauschvorschau",
    youGive: "Sie geben",
    bonus: "Bonus",
    noFees: "Keine Gebühren",
    instant: "Tausch ist sofort",
    walletPage: "Geldbörse",
    receiveAddresses: "Empfangsadressen",
    sendCryptoInfo:
      "Senden Sie Krypto an diese Adressen, um Blumen zu erhalten",
    address: "Adresse",
    exchangeCrypto: "Krypto tauschen",
    afterSendingConfirm:
      "Nach dem Senden von Krypto bestätigen Sie den Tausch hier",
    networkLabel: "Netzwerk",
    amountSent: "Gesendeter Betrag",
    youWillReceiveFlowers: "Sie erhalten",
    minimum: "Minimum",
    confirmExchange: "Tausch bestätigen",
    important: "Wichtig",
    verifyAddressWarning: "Überprüfen Sie die Adresse vor dem Senden",
    cryptoIrreversible: "Krypto-Transaktionen sind nicht umkehrbar",
    useCorrectNetwork: "Verwenden Sie das richtige Netzwerk (Solana oder TON)",
    minAmountWarning: "Mindestbetrag: 5$ (40.000 Blumen)",
    exchangeAfterReceipt: "Tausch erfolgt nach Erhalt Ihrer Transaktion",
    exchangeQuestion: "{amount} {currency} gegen {flowers} Blumen tauschen?",
    received: "Sie haben {flowers} Blumen erhalten!",
    copied2: "Adresse in die Zwischenablage kopiert",
    invalidAmount: "Ungültiger Betrag",
    selectNetworkError: "Bitte wählen Sie ein Netzwerk",
    selectExchangeType: "Bitte wählen Sie einen Tauschtyp",
    minBVRError: "Mindestbetrag ist 100 BVR für 0.01 Blume",
    onSolana: "auf Solana",
    networkOnlyForBVR: "Einziges Netzwerk für BVR-Auszahlungen",
    minimum2: "Min",
    fillAllFields: "Bitte füllen Sie alle Felder aus",
    passwordsDontMatch: "Passwörter stimmen nicht überein",
    passwordTooShort: "Passwort muss mindestens 6 Zeichen lang sein",
    createAccount: "Konto Erstellen",
    login: "Anmelden",
    email: "E-Mail",
    enterEmail: "Geben Sie Ihre E-Mail ein",
    password: "Passwort",
    enterPassword: "Geben Sie Ihr Passwort ein",
    confirmPassword: "Passwort Bestätigen",
    confirmPasswordPlaceholder: "Bestätigen Sie Ihr Passwort",
    sponsorCode: "Sponsorcode (optional)",
    enterSponsorCode: "Geben Sie den Sponsorcode ein",
    register: "Registrieren",
    loginButton: "Anmelden",
    alreadyHaveAccount: "Sie haben bereits ein Konto? Melden Sie sich an",
    dontHaveAccount: "Sie haben kein Konto? Registrieren Sie sich",
    leaderboard: "Rangliste",
    diamondLeaderboard: "Diamanten-Rangliste",
    topProducers: "Top Jahresproduzenten",
    you: "Sie",
    joinBeeMinorPlayWin: "Tritt BeeMinor bei, spiele und gewinne",
    forgotPassword: "Passwort vergessen?",
    sendCode: "Code senden",
    resetPasswordTitle: "Passwort zurücksetzen",
    resetButton: "Zurücksetzen",
    resetCode: "Rücksetzungscode",
    enterResetCode: "Geben Sie den per E-Mail erhaltenen Code ein",
    newPassword: "Neues Passwort",
    enterNewPassword: "Geben Sie Ihr neues Passwort ein",
    confirmNewPassword: "Neues Passwort bestätigen",
    confirmYourNewPassword: "Bestätigen Sie Ihr neues Passwort",
    backToLogin: "Zurück zur Anmeldung",
    emailSent: "E-Mail gesendet",
    resetCodeSentTo: "Ein Rücksetzungscode wurde gesendet an",
    checkLogsForCode: "Überprüfen Sie Ihre Logs für den Testcode:",
    passwordResetSuccess:
      "Ihr Passwort wurde erfolgreich zurückgesetzt. Sie können sich jetzt anmelden.",
    canNowLogin: "Sie können sich jetzt anmelden",
    winChances: "Gewinnchancen",
    claimFailed: "Anspruch fehlgeschlagen",
  },
  it: {
    home: "Home",
    shop: "Negozio",
    hive: "Alveare",
    alveole: "Alveolo",
    menu: "Menu",
    tasks: "Compiti",
    honey: "Miele",
    flowers: "Fiori",
    diamonds: "Diamanti",
    bees: "Api",
    honeyPerHour: "Miele/Ora",
    honeyPerSec: "Miele/Sec",
    faq: "FAQ",
    help: "Aiuto",
    accountDetails: "Dettagli account",
    transactionHistory: "Cronologia",
    loading: "Caricamento...",
    babyBee: "Ape Bambina",
    workerBee: "Ape Operaia",
    eliteBee: "Ape Elite",
    royalBee: "Ape Reale",
    queenBee: "Ape Regina",
    buy: "Acquista",
    exchange: "Scambia",
    withdraw: "Preleva",
    roulette: "Roulette",
    wallet: "Portafoglio",
    missions: "Missioni",
    invite: "Invita",
    referrals: "Referral",
    myReferralCode: "Il mio codice referral",
    inviteLink: "Link di invito",
    friendsInvited: "Amici invitati",
    totalEarnings: "Guadagni totali",
    myResources: "Le Mie Risorse",
    buyFlowers: "Acquista Fiori",
    smallPack: "Pacchetto Piccolo",
    mediumPack: "Pacchetto Medio",
    largePack: "Pacchetto Grande",
    giantPack: "Pacchetto Gigante",
    owned: "Posseduto",
    statistics: "Statistiche di Produzione",
    totalProduction: "Produzione totale",
    totalBees: "Numero totale di api",
    maxCapacity: "Capacità massima",
    close: "Chiudi",
    chooseLanguage: "Scegli lingua",
    spinTheWheel: "Gira la ruota per vincere premi",
    withdrawCrypto: "Preleva i tuoi diamanti in crypto",
    exchangeResources: "Scambia le tue risorse con fiori",
    receiveAndExchange: "Ricevi crypto e scambia con fiori",
    selectNetwork: "Seleziona una rete",
    walletAddress: "Indirizzo portafoglio",
    withdrawAmount: "Importo del prelievo",
    summary: "Riepilogo",
    amount: "Importo",
    fees: "Commissioni",
    youWillReceive: "Riceverai",
    importantInfo: "Informazioni importanti",
    error: "Errore",
    success: "Successo",
    confirmation: "Conferma",
    cancel: "Annulla",
    confirm: "Conferma",
    enterWalletAddress: "Inserisci un indirizzo di portafoglio",
    enterValidAmount: "Inserisci un importo valido",
    notEnoughDiamonds: "Non hai abbastanza diamanti",
    notEnoughBVR: "Non hai abbastanza BVR",
    withdrawalSubmitted:
      "La tua richiesta di prelievo è stata inviata. Riceverai i tuoi fondi entro 24-48h.",
    bvrWithdrawalSubmitted:
      "La tua richiesta di prelievo BVR è stata inviata. Riceverai i tuoi fondi su Solana entro 24-48h.",
    availableBalance: "Saldo disponibile",
    network: "Rete",
    minimumWithdraw: "Min",
    conversionRate: "Tasso di conversione",
    processingTime: "Tempo di elaborazione",
    verifyAddress: "Verifica bene il tuo indirizzo prima di confermare",
    coldWalletRequired: "ATTENZIONE - Cold Wallet Obbligatorio",
    inviteFriendBonus: "Invita un amico",
    copyReferralCode: "Copiato!",
    copyInviteLink: "Copia link di invito",
    copied: "Codice referral copiato negli appunti",
    alreadyClaimed: "Hai già richiesto questa ricompensa",
    missionIncomplete: "Missione incompleta",
    rewardClaimed: "Ricompensa richiesta!",
    referralBonus: "Bonus referral",
    perFriend: "per amico invitato",
    firstPurchaseBonus: "se il tuo referral fa un 1° acquisto",
    firstDepositPercent: "dell'importo del primo deposito",
    lifetimePercent: "a vita su tutti i depositi successivi",
    inviteFriends: "Invita",
    progress: "Progresso",
    claim: "Richiedi",
    claimed: "Richiesto",
    inProgress: "In corso",
    noReferrals: "Nessun referral ancora",
    inviteToEarn: "Invita i tuoi amici per iniziare a guadagnare ricompense!",
    joinedOn: "Iscritto il",
    totalDeposits: "Depositi totali",
    firstDeposit: "Primo deposito",
    lifetimeEarnings: "Guadagni a vita",
    bvr: "BVR",
    cryptoWithdraw: "Prelievo Crypto",
    account: "Account",
    history: "Cronologia",
    sellHoney: "Vendi miele",
    honeyExchange: "Scambio di miele",
    honeyExchangeRate: "1 miel (USDT) = 1 💎 diamante",
    quickSell: "Vendita rapida",
    sellAllHoney: "Vendi tutto il miele",
    alveoleLevels: "Livelli di Alveare",
    level: "Livello",
    unlocked: "✓ Sbloccato",
    capacity: "Capacità",
    cost: "Costo",
    unlock: "Sblocca",
    currentLevel: "Livello attuale",
    alveoleUnlocked: "Alveare livello {level} sbloccato!",
    insufficientFlowers: "Fiori insufficienti",
    needFlowers: "Hai bisogno di {amount} fiori.",
    insufficientHoney: "Miele insufficiente",
    needMinHoney: "Hai bisogno di almeno 100 miele per vendere.",
    sold: "Venduto!",
    transactionSuccess: "Transazione riuscita!",
    transactionFailed: "Transazione fallita",
    diamondExchangeRate: "100 diamanti = 0.01 fiori",
    cryptoWithdrawPage: "Prelievo Crypto",
    ticketsAvailable: "Ticket disponibili",
    spinning: "Girando...",
    noTickets: "Nessun ticket",
    spinWheel: "GIRA LA RUOTA",
    youWon: "🎉 Hai vinto! 🎉",
    howToGetTickets: "Come ottenere ticket?",
    buyFlowersTicketInfo:
      "Acquista fiori nel negozio! Ogni acquisto di $10 ti dà 1 ticket.",
    exchangePage: "Scambio",
    yourBalances: "I tuoi saldi",
    exchangeType: "Tipo di scambio",
    diamondsToFlowers: "Diamanti a Fiori",
    bvrToFlowers: "BVR a Fiori",
    amountToExchange: "Importo da scambiare",
    exchangePreview: "Anteprima dello scambio",
    youGive: "Dai",
    bonus: "Bonus",
    noFees: "Nessuna commissione",
    instant: "Lo scambio è istantaneo",
    walletPage: "Portafoglio",
    receiveAddresses: "Indirizzi di ricezione",
    sendCryptoInfo: "Invia crypto a questi indirizzi per ricevere fiori",
    address: "Indirizzo",
    exchangeCrypto: "Scambia crypto",
    afterSendingConfirm: "Dopo aver inviato crypto, conferma lo scambio qui",
    networkLabel: "Rete",
    amountSent: "Importo inviato",
    youWillReceiveFlowers: "Riceverai",
    minimum: "Minimo",
    confirmExchange: "Conferma scambio",
    important: "Importante",
    verifyAddressWarning: "Verifica l'indirizzo prima di inviare",
    cryptoIrreversible: "Le transazioni crypto sono irreversibili",
    useCorrectNetwork: "Usa la rete corretta (Solana o TON)",
    minAmountWarning: "Importo minimo: $5 (40.000 fiori)",
    exchangeAfterReceipt:
      "Lo scambio avviene dopo aver ricevuto la tua transazione",
    exchangeQuestion: "Scambiare {amount} {currency} per {flowers} fiori?",
    received: "Hai ricevuto {flowers} fiori!",
    copied2: "Indirizzo copiato negli appunti",
    invalidAmount: "Importo non valido",
    selectNetworkError: "Seleziona una rete",
    selectExchangeType: "Seleziona un tipo di scambio",
    minBVRError: "L'importo minimo è 100 BVR per ottenere 0.01 fiore",
    onSolana: "su Solana",
    networkOnlyForBVR: "Unica rete per prelievi BVR",
    minimum2: "Min",
    fillAllFields: "Per favore compila tutti i campi",
    passwordsDontMatch: "Le password non corrispondono",
    passwordTooShort: "La password deve contenere almeno 6 caratteri",
    createAccount: "Crea Account",
    login: "Accedi",
    email: "Email",
    enterEmail: "Inserisci la tua email",
    password: "Password",
    enterPassword: "Inserisci la tua password",
    confirmPassword: "Conferma Password",
    confirmPasswordPlaceholder: "Conferma la tua password",
    sponsorCode: "Codice sponsor (opzionale)",
    enterSponsorCode: "Inserisci il codice sponsor",
    register: "Registrati",
    loginButton: "Accedi",
    alreadyHaveAccount: "Hai già un account? Accedi",
    dontHaveAccount: "Non hai un account? Registrati",
    leaderboard: "Classifica",
    diamondLeaderboard: "Classifica Diamanti",
    topProducers: "Top Produttori Annuali",
    you: "Tu",
    joinBeeMinorPlayWin: "Unisciti a BeeMinor, gioca e vinci",
    forgotPassword: "Password dimenticata?",
    sendCode: "Invia codice",
    resetPasswordTitle: "Reimposta password",
    resetButton: "Reimposta",
    resetCode: "Codice di reimpostazione",
    enterResetCode: "Inserisci il codice ricevuto via email",
    newPassword: "Nuova password",
    enterNewPassword: "Inserisci la tua nuova password",
    confirmNewPassword: "Conferma nuova password",
    confirmYourNewPassword: "Conferma la tua nuova password",
    backToLogin: "Torna al login",
    emailSent: "Email inviata",
    resetCodeSentTo: "Un codice di reimpostazione è stato inviato a",
    checkLogsForCode: "Controlla i tuoi log per il codice di test:",
    passwordResetSuccess:
      "La tua password è stata reimpostata con successo. Ora puoi accedere.",
    canNowLogin: "Ora puoi accedere",
    winChances: "Probabilità di vincita",
    claimFailed: "Richiesta fallita",
  },
  pt: {
    home: "Início",
    shop: "Loja",
    hive: "Colmeia",
    alveole: "Alvéolo",
    menu: "Menu",
    tasks: "Tarefas",
    honey: "Mel",
    flowers: "Flores",
    diamonds: "Diamantes",
    bees: "Abelhas",
    honeyPerHour: "Mel/Hora",
    honeyPerSec: "Mel/Seg",
    faq: "FAQ",
    help: "Ajuda",
    accountDetails: "Detalhes da conta",
    transactionHistory: "Histórico",
    loading: "Carregando...",
    babyBee: "Abelha Bebê",
    workerBee: "Abelha Operária",
    eliteBee: "Abelha Elite",
    royalBee: "Abelha Real",
    queenBee: "Abelha Rainha",
    buy: "Comprar",
    exchange: "Trocar",
    withdraw: "Retirar",
    roulette: "Roleta",
    wallet: "Carteira",
    missions: "Missões",
    invite: "Convidar",
    referrals: "Indicações",
    myReferralCode: "Meu código de indicação",
    inviteLink: "Link de convite",
    friendsInvited: "Amigos convidados",
    totalEarnings: "Ganhos totais",
    myResources: "Meus Recursos",
    buyFlowers: "Comprar Flores",
    smallPack: "Pacote Pequeno",
    mediumPack: "Pacote Médio",
    largePack: "Pacote Grande",
    giantPack: "Pacote Gigante",
    owned: "Possuído",
    statistics: "Estatísticas de Produção",
    totalProduction: "Produção total",
    totalBees: "Número total de abelhas",
    maxCapacity: "Capacidade máxima",
    close: "Fechar",
    chooseLanguage: "Escolher idioma",
    spinTheWheel: "Gire a roleta para ganhar prêmios",
    withdrawCrypto: "Retire seus diamantes em crypto",
    exchangeResources: "Troque seus recursos por flores",
    receiveAndExchange: "Receba crypto e troque por flores",
    selectNetwork: "Selecione uma rede",
    walletAddress: "Endereço da carteira",
    withdrawAmount: "Valor do saque",
    summary: "Resumo",
    amount: "Valor",
    fees: "Taxas",
    youWillReceive: "Você receberá",
    importantInfo: "Informações importantes",
    error: "Erro",
    success: "Sucesso",
    confirmation: "Confirmação",
    cancel: "Cancelar",
    confirm: "Confirmar",
    enterWalletAddress: "Por favor insira um endereço de carteira",
    enterValidAmount: "Por favor insira um valor válido",
    notEnoughDiamonds: "Você não tem diamantes suficientes",
    notEnoughBVR: "Você não tem BVR suficientes",
    withdrawalSubmitted:
      "Seu pedido de saque foi enviado. Você receberá seus fundos em 24-48h.",
    bvrWithdrawalSubmitted:
      "Seu pedido de saque BVR foi enviado. Você receberá seus fundos na Solana em 24-48h.",
    availableBalance: "Saldo disponível",
    network: "Rede",
    minimumWithdraw: "Mín",
    conversionRate: "Taxa de conversão",
    processingTime: "Tempo de processamento",
    verifyAddress: "Verifique bem seu endereço antes de confirmar",
    coldWalletRequired: "ATENÇÃO - Cold Wallet Obrigatória",
    inviteFriendBonus: "Convidar um amigo",
    copyReferralCode: "Copiado!",
    copyInviteLink: "Copiar link de convite",
    copied: "Código de indicação copiado para a área de transferência",
    alreadyClaimed: "Você já reivindicou esta recompensa",
    missionIncomplete: "Missão incompleta",
    rewardClaimed: "Recompensa reivindicada!",
    referralBonus: "Bônus de indicação",
    perFriend: "por amigo convidado",
    firstPurchaseBonus: "se sua indicação fizer uma 1ª compra",
    firstDepositPercent: "do valor do primeiro depósito",
    lifetimePercent: "vitalício em todos os depósitos seguintes",
    inviteFriends: "Convidar",
    progress: "Progresso",
    claim: "Reivindicar",
    claimed: "Reivindicado",
    inProgress: "Em progresso",
    noReferrals: "Nenhuma indicação ainda",
    inviteToEarn: "Convide seus amigos para começar a ganhar recompensas!",
    joinedOn: "Entrou em",
    totalDeposits: "Depósitos totais",
    firstDeposit: "Primeiro depósito",
    lifetimeEarnings: "Ganhos vitalícios",
    bvr: "BVR",
    cryptoWithdraw: "Saque Crypto",
    account: "Conta",
    history: "Histórico",
    sellHoney: "Vender mel",
    honeyExchange: "Troca de mel",
    honeyExchangeRate: "1 miel (USDT) = 1 💎 diamante",
    quickSell: "Venda rápida",
    sellAllHoney: "Vender todo o mel",
    alveoleLevels: "Níveis de Alvéolos",
    level: "Nível",
    unlocked: "✓ Desbloqueado",
    capacity: "Capacidade",
    cost: "Custo",
    unlock: "Desbloquear",
    currentLevel: "Nível atual",
    alveoleUnlocked: "Alvéolo nível {level} desbloqueado!",
    insufficientFlowers: "Flores insuficientes",
    needFlowers: "Você precisa de {amount} flores.",
    insufficientHoney: "Mel insuficiente",
    needMinHoney: "Você precisa de pelo menos 100 mel para vender.",
    sold: "Vendido!",
    transactionSuccess: "Transação bem-sucedida!",
    transactionFailed: "Transação falhou",
    diamondExchangeRate: "100 diamantes = 0.01 flores",
    cryptoWithdrawPage: "Saque Crypto",
    ticketsAvailable: "Tickets disponíveis",
    spinning: "Girando...",
    noTickets: "Sem tickets",
    spinWheel: "GIRAR A ROLETA",
    youWon: "🎉 Você ganhou! 🎉",
    howToGetTickets: "Como obter tickets?",
    buyFlowersTicketInfo:
      "Compre flores na loja! Cada compra de $10 dá 1 ticket.",
    exchangePage: "Troca",
    yourBalances: "Seus saldos",
    exchangeType: "Tipo de troca",
    diamondsToFlowers: "Diamantes para Flores",
    bvrToFlowers: "BVR para Flores",
    amountToExchange: "Valor a trocar",
    exchangePreview: "Prévia da troca",
    youGive: "Você dá",
    bonus: "Bônus",
    noFees: "Sem taxas",
    instant: "A troca é instantânea",
    walletPage: "Carteira",
    receiveAddresses: "Endereços de recebimento",
    sendCryptoInfo: "Envie crypto para estes endereços para receber flores",
    address: "Endereço",
    exchangeCrypto: "Trocar crypto",
    afterSendingConfirm: "Após enviar crypto, confirme a troca aqui",
    networkLabel: "Rede",
    amountSent: "Valor enviado",
    youWillReceiveFlowers: "Você receberá",
    minimum: "Mínimo",
    confirmExchange: "Confirmar troca",
    important: "Importante",
    verifyAddressWarning: "Verifique o endereço antes de enviar",
    cryptoIrreversible: "Transações crypto são irreversíveis",
    useCorrectNetwork: "Use a rede correta (Solana ou TON)",
    minAmountWarning: "Valor mínimo: $5 (40.000 flores)",
    exchangeAfterReceipt: "A troca ocorre após receber sua transação",
    exchangeQuestion: "Trocar {amount} {currency} por {flowers} flores?",
    received: "Você recebeu {flowers} flores!",
    copied2: "Endereço copiado para a área de transferência",
    invalidAmount: "Valor inválido",
    selectNetworkError: "Por favor selecione uma rede",
    selectExchangeType: "Por favor selecione um tipo de troca",
    minBVRError: "O valor mínimo é 100 BVR para obter 0.01 flor",
    onSolana: "na Solana",
    networkOnlyForBVR: "Única rede para saques BVR",
    minimum2: "Mín",
    fillAllFields: "Por favor preencha todos os campos",
    passwordsDontMatch: "As senhas não correspondem",
    passwordTooShort: "A senha deve ter pelo menos 6 caracteres",
    createAccount: "Criar Conta",
    login: "Entrar",
    email: "Email",
    enterEmail: "Digite seu email",
    password: "Senha",
    enterPassword: "Digite sua senha",
    confirmPassword: "Confirmar Senha",
    confirmPasswordPlaceholder: "Confirme sua senha",
    sponsorCode: "Código de patrocinador (opcional)",
    enterSponsorCode: "Digite o código de patrocinador",
    register: "Registrar",
    loginButton: "Entrar",
    alreadyHaveAccount: "Já tem uma conta? Entre",
    dontHaveAccount: "Não tem uma conta? Cadastre-se",
    leaderboard: "Classificação",
    diamondLeaderboard: "Classificação de Diamantes",
    topProducers: "Melhores Produtores Anuais",
    you: "Você",
    joinBeeMinorPlayWin: "Junte-se ao BeeMinor, jogue e ganhe",
    forgotPassword: "Esqueceu a senha?",
    sendCode: "Enviar código",
    resetPasswordTitle: "Redefinir senha",
    resetButton: "Redefinir",
    resetCode: "Código de redefinição",
    enterResetCode: "Digite o código recebido por email",
    newPassword: "Nova senha",
    enterNewPassword: "Digite sua nova senha",
    confirmNewPassword: "Confirmar nova senha",
    confirmYourNewPassword: "Confirme sua nova senha",
    backToLogin: "Voltar ao login",
    emailSent: "Email enviado",
    resetCodeSentTo: "Um código de redefinição foi enviado para",
    checkLogsForCode: "Verifique seus logs para o código de teste:",
    passwordResetSuccess:
      "Sua senha foi redefinida com sucesso. Você pode fazer login agora.",
    canNowLogin: "Você pode fazer login agora",
    winChances: "Chances de ganhar",
    claimFailed: "Falha ao reivindicar",
  },
  ru: {
    home: "Главная",
    shop: "Магазин",
    hive: "Улей",
    alveole: "Ячейка",
    menu: "Меню",
    tasks: "Задачи",
    honey: "Мёд",
    flowers: "Цветы",
    diamonds: "Алмазы",
    bees: "Пчёлы",
    honeyPerHour: "Мёд/Час",
    honeyPerSec: "Мёд/Сек",
    faq: "FAQ",
    help: "Помощь",
    accountDetails: "Детали аккаунта",
    transactionHistory: "История",
    loading: "Загрузка...",
    babyBee: "Пчёлка",
    workerBee: "Рабочая пчела",
    eliteBee: "Элитная пчела",
    royalBee: "Королевская пчела",
    queenBee: "Пчелиная матка",
    buy: "Купить",
    exchange: "Обменять",
    withdraw: "Вывести",
    roulette: "Рулетка",
    wallet: "Кошелёк",
    missions: "Миссии",
    invite: "Пригласить",
    referrals: "Рефералы",
    myReferralCode: "Мой реферальный код",
    inviteLink: "Ссылка приглашения",
    friendsInvited: "Приглашённые друзья",
    totalEarnings: "Общий заработок",
    myResources: "Мои Ресурсы",
    buyFlowers: "Купить Цветы",
    smallPack: "Малый Пакет",
    mediumPack: "Средний Пакет",
    largePack: "Большой Пакет",
    giantPack: "Гигантский Пакет",
    owned: "Владение",
    statistics: "Статистика Производства",
    totalProduction: "Общее производство",
    totalBees: "Общее количество пчёл",
    maxCapacity: "Максимальная вместимость",
    close: "Закрыть",
    chooseLanguage: "Выбрать язык",
    spinTheWheel: "Крутите колесо, чтобы выиграть призы",
    withdrawCrypto: "Выведите свои алмазы в крипту",
    exchangeResources: "Обменяйте свои ресурсы на цветы",
    receiveAndExchange: "Получите крипту и обменяйте на цветы",
    selectNetwork: "Выберите сеть",
    walletAddress: "Адрес кошелька",
    withdrawAmount: "Сумма вывода",
    summary: "Итого",
    amount: "Сумма",
    fees: "Комиссия",
    youWillReceive: "Вы получите",
    importantInfo: "Важная информация",
    error: "Ошибка",
    success: "Успех",
    confirmation: "Подтверждение",
    cancel: "Отмена",
    confirm: "Подтвердить",
    enterWalletAddress: "Пожалуйста, введите адрес кошелька",
    enterValidAmount: "Пожалуйста, введите корректную сумму",
    notEnoughDiamonds: "У вас недостаточно алмазов",
    notEnoughBVR: "У вас недостаточно BVR",
    withdrawalSubmitted:
      "Ваш запрос на вывод отправлен. Вы получите свои средства в течение 24-48ч.",
    bvrWithdrawalSubmitted:
      "Ваш запрос на вывод BVR отправлен. Вы получите свои средства в Solana в течение 24-48ч.",
    availableBalance: "Доступный баланс",
    network: "Сеть",
    minimumWithdraw: "Мин",
    conversionRate: "Курс конвертации",
    processingTime: "Время обработки",
    verifyAddress: "Пожалуйста, проверьте свой адрес перед подтверждением",
    coldWalletRequired: "ВНИМАНИЕ - Холодный Кошелёк Обязателен",
    inviteFriendBonus: "Пригласить друга",
    copyReferralCode: "Скопировано!",
    copyInviteLink: "Скопировать ссылку приглашения",
    copied: "Реферальный код скопирован в буфер обмена",
    alreadyClaimed: "Вы уже получили эту награду",
    missionIncomplete: "Миссия не завершена",
    rewardClaimed: "Награда получена!",
    referralBonus: "Реферальный бонус",
    perFriend: "за приглашённого друга",
    firstPurchaseBonus: "если ваш реферал сделает 1-ю покупку",
    firstDepositPercent: "от суммы первого депозита",
    lifetimePercent: "пожизненно на все следующие депозиты",
    inviteFriends: "Пригласить",
    progress: "Прогресс",
    claim: "Получить",
    claimed: "Получено",
    inProgress: "В процессе",
    noReferrals: "Рефералов пока нет",
    inviteToEarn: "Приглашайте друзей, чтобы начать зарабатывать награды!",
    joinedOn: "Присоединился",
    totalDeposits: "Всего депозитов",
    firstDeposit: "Первый депозит",
    lifetimeEarnings: "Заработок за всё время",
    bvr: "BVR",
    cryptoWithdraw: "Вывод Крипты",
    account: "Аккаунт",
    history: "История",
    sellHoney: "Продать мёд",
    honeyExchange: "Обмен мёда",
    honeyExchangeRate: "1 miel (USDT) = 1 💎 алмаз",
    quickSell: "Быстрая продажа",
    sellAllHoney: "Продать весь мёд",
    alveoleLevels: "Уровни улья",
    level: "Уровень",
    unlocked: "✓ Разблокировано",
    capacity: "Вместимость",
    cost: "Стоимость",
    unlock: "Разблокировать",
    currentLevel: "Текущий уровень",
    alveoleUnlocked: "Улей уровень {level} разблокирован!",
    insufficientFlowers: "Недостаточно цветов",
    needFlowers: "Вам нужно {amount} цветов.",
    insufficientHoney: "Недостаточно мёда",
    needMinHoney: "Вам нужно минимум 100 мёда для продажи.",
    sold: "Продано!",
    transactionSuccess: "Транзакция успешна!",
    transactionFailed: "Транзакция не удалась",
    diamondExchangeRate: "100 алмазов = 0.01 цветов",
    cryptoWithdrawPage: "Вывод Крипты",
    ticketsAvailable: "Доступные тикеты",
    spinning: "Вращается...",
    noTickets: "Нет тикетов",
    spinWheel: "КРУТИТЬ КОЛЕСО",
    youWon: "🎉 Вы выиграли! 🎉",
    howToGetTickets: "Как получить тикеты?",
    buyFlowersTicketInfo:
      "Покупайте цветы в магазине! Каждая покупка на $10 даёт 1 тикет.",
    exchangePage: "Обмен",
    yourBalances: "Ваши балансы",
    exchangeType: "Тип обмена",
    diamondsToFlowers: "Алмазы на Цветы",
    bvrToFlowers: "BVR на Цветы",
    amountToExchange: "Сумма обмена",
    exchangePreview: "Предпросмотр обмена",
    youGive: "Вы даёте",
    bonus: "Бонус",
    noFees: "Без комиссии",
    instant: "Обмен мгновенный",
    walletPage: "Кошелёк",
    receiveAddresses: "Адреса получения",
    sendCryptoInfo: "Отправьте крипту на эти адреса для получения цветов",
    address: "Адрес",
    exchangeCrypto: "Обменять крипту",
    afterSendingConfirm: "После отправки крипты подтвердите обмен здесь",
    networkLabel: "Сеть",
    amountSent: "Отправленная сумма",
    youWillReceiveFlowers: "Вы получите",
    minimum: "Минимум",
    confirmExchange: "Подтвердить обмен",
    important: "Важно",
    verifyAddressWarning: "Проверьте адрес перед отправкой",
    cryptoIrreversible: "Крипто-транзакции необратимы",
    useCorrectNetwork: "Используйте правильную сеть (Solana или TON)",
    minAmountWarning: "Минимальная сумма: $5 (40.000 цветов)",
    exchangeAfterReceipt: "Обмен происходит после получения вашей транзакции",
    exchangeQuestion: "Обменять {amount} {currency} на {flowers} цветов?",
    received: "Вы получили {flowers} цветов!",
    copied2: "Адрес скопирован в буфер обмена",
    invalidAmount: "Неверная сумма",
    selectNetworkError: "Пожалуйста, выберите сеть",
    selectExchangeType: "Пожалуйста, выберите тип обмена",
    minBVRError: "Минимальная сумма 100 BVR для получения 0.01 цветка",
    onSolana: "в Solana",
    networkOnlyForBVR: "Единственная сеть для вывода BVR",
    minimum2: "Мин",
    fillAllFields: "Пожалуйста, заполните все поля",
    passwordsDontMatch: "Пароли не совпадают",
    passwordTooShort: "Пароль должен содержать не менее 6 символов",
    createAccount: "Создать Аккаунт",
    login: "Вход",
    email: "Email",
    enterEmail: "Введите ваш email",
    password: "Пароль",
    enterPassword: "Введите ваш пароль",
    confirmPassword: "Подтвердите Пароль",
    confirmPasswordPlaceholder: "Подтвердите ваш пароль",
    sponsorCode: "Код спонсора (опционально)",
    enterSponsorCode: "Введите код спонсора",
    register: "Зарегистрироваться",
    loginButton: "Войти",
    alreadyHaveAccount: "Уже есть аккаунт? Войдите",
    dontHaveAccount: "Нет аккаунта? Зарегистрируйтесь",
    leaderboard: "Рейтинг",
    diamondLeaderboard: "Рейтинг Алмазов",
    topProducers: "Топ Годовых Производителей",
    you: "Вы",
    joinBeeMinorPlayWin: "Присоединяйтесь к BeeMinor, играйте и выигрывайте",
    forgotPassword: "Забыли пароль?",
    sendCode: "Отправить код",
    resetPasswordTitle: "Сбросить пароль",
    resetButton: "Сбросить",
    resetCode: "Код сброса",
    enterResetCode: "Введите код, полученный по электронной почте",
    newPassword: "Новый пароль",
    enterNewPassword: "Введите ваш новый пароль",
    confirmNewPassword: "Подтвердите новый пароль",
    confirmYourNewPassword: "Подтвердите ваш новый пароль",
    backToLogin: "Вернуться к входу",
    emailSent: "Email отправлен",
    resetCodeSentTo: "Код сброса был отправлен на",
    checkLogsForCode: "Проверьте ваши логи для тестового кода:",
    passwordResetSuccess:
      "Ваш пароль был успешно сброшен. Теперь вы можете войти.",
    canNowLogin: "Теперь вы можете войти",
    winChances: "Шансы на выигрыш",
    claimFailed: "Не удалось получить",
  },
  ar: {
    home: "الرئيسية",
    shop: "المتجر",
    hive: "الخلية",
    alveole: "قرص العسل",
    menu: "القائمة",
    tasks: "المهام",
    honey: "العسل",
    flowers: "الزهور",
    diamonds: "الماس",
    bees: "النحل",
    honeyPerHour: "عسل/ساعة",
    honeyPerSec: "عسل/ثانية",
    faq: "الأسئلة الشائعة",
    help: "مساعدة",
    accountDetails: "تفاصيل الحساب",
    transactionHistory: "السجل",
    loading: "جارٍ التحميل...",
    babyBee: "نحلة صغيرة",
    workerBee: "نحلة عاملة",
    eliteBee: "نحلة نخبة",
    royalBee: "نحلة ملكية",
    queenBee: "ملكة النحل",
    buy: "شراء",
    exchange: "تبادل",
    withdraw: "سحب",
    roulette: "الروليت",
    wallet: "المحفظة",
    missions: "المهام",
    invite: "دعوة",
    referrals: "الإحالات",
    myReferralCode: "رمز الإحالة الخاص بي",
    inviteLink: "رابط الدعوة",
    friendsInvited: "الأصدقاء المدعوون",
    totalEarnings: "إجمالي الأرباح",
    myResources: "مواردي",
    buyFlowers: "شراء الزهور",
    smallPack: "حزمة صغيرة",
    mediumPack: "حزمة متوسطة",
    largePack: "حزمة كبيرة",
    giantPack: "حزمة عملاقة",
    owned: "مملوك",
    statistics: "إحصائيات الإنتاج",
    totalProduction: "الإنتاج الإجمالي",
    totalBees: "إجمالي عدد النحل",
    maxCapacity: "السعة القصوى",
    close: "إغلاق",
    chooseLanguage: "اختر اللغة",
    spinTheWheel: "أدر العجلة لتفوز بالجوائز",
    withdrawCrypto: "اسحب ماساتك بالعملات المشفرة",
    exchangeResources: "بادل مواردك بالزهور",
    receiveAndExchange: "استلم العملات المشفرة وبادلها بالزهور",
    selectNetwork: "اختر الشبكة",
    walletAddress: "عنوان المحفظة",
    withdrawAmount: "مبلغ السحب",
    summary: "ملخص",
    amount: "المبلغ",
    fees: "الرسوم",
    youWillReceive: "سوف تستلم",
    importantInfo: "معلومات مهمة",
    error: "خطأ",
    success: "نجح",
    confirmation: "تأكيد",
    cancel: "إلغاء",
    confirm: "تأكيد",
    enterWalletAddress: "الرجاء إدخال عنوان المحفظة",
    enterValidAmount: "الرجاء إدخال مبلغ صالح",
    notEnoughDiamonds: "ليس لديك ما يكفي من الماس",
    notEnoughBVR: "ليس لديك ما يكفي من BVR",
    withdrawalSubmitted:
      "تم إرسال طلب السحب الخاص بك. سوف تستلم أموالك خلال 24-48 ساعة.",
    bvrWithdrawalSubmitted:
      "تم إرسال طلب سحب BVR الخاص بك. سوف تستلم أموالك على Solana خلال 24-48 ساعة.",
    availableBalance: "الرصيد المتاح",
    network: "الشبكة",
    minimumWithdraw: "الحد الأدنى",
    conversionRate: "سعر التحويل",
    processingTime: "وقت المعالجة",
    verifyAddress: "يرجى التحقق من عنوانك قبل التأكيد",
    coldWalletRequired: "تحذير - المحفظة الباردة مطلوبة",
    inviteFriendBonus: "دعوة صديق",
    copyReferralCode: "تم النسخ!",
    copyInviteLink: "نسخ رابط الدعوة",
    copied: "تم نسخ رمز الإحالة إلى الحافظة",
    alreadyClaimed: "لقد طالبت بهذه المكافأة بالفعل",
    missionIncomplete: "المهمة غير مكتملة",
    rewardClaimed: "تم الحصول على المكافأة!",
    referralBonus: "مكافأة الإحالة",
    perFriend: "لكل صديق مدعو",
    firstPurchaseBonus: "إذا قام الشخص المحال بأول عملية شراء",
    firstDepositPercent: "من مبلغ الإيداع الأول",
    lifetimePercent: "مدى الحياة على جميع الودائع التالية",
    inviteFriends: "دعوة",
    progress: "التقدم",
    claim: "المطالبة",
    claimed: "تم المطالبة",
    inProgress: "قيد التنفيذ",
    noReferrals: "لا توجد إحالات حتى الآن",
    inviteToEarn: "ادع أصدقاءك لبدء كسب المكافآت!",
    joinedOn: "انضم في",
    totalDeposits: "إجمالي الودائع",
    firstDeposit: "الإيداع الأول",
    lifetimeEarnings: "الأرباح مدى الحياة",
    bvr: "BVR",
    cryptoWithdraw: "سحب العملات المشفرة",
    account: "الحساب",
    history: "السجل",
    sellHoney: "بيع العسل",
    honeyExchange: "تبادل العسل",
    honeyExchangeRate: "1 miel (USDT) = 1 💎 ماسة",
    quickSell: "بيع سريع",
    sellAllHoney: "بيع كل العسل",
    alveoleLevels: "مستويات قرص العسل",
    level: "المستوى",
    unlocked: "✓ تم إلغاء القفل",
    capacity: "السعة",
    cost: "التكلفة",
    unlock: "إلغاء القفل",
    currentLevel: "المستوى الحالي",
    alveoleUnlocked: "تم إلغاء قفل قرص العسل المستوى {level}!",
    insufficientFlowers: "زهور غير كافية",
    needFlowers: "تحتاج إلى {amount} زهرة.",
    insufficientHoney: "عسل غير كافٍ",
    needMinHoney: "تحتاج إلى ما لا يقل عن 100 عسل للبيع.",
    sold: "تم البيع!",
    transactionSuccess: "نجحت العملية!",
    transactionFailed: "فشلت العملية",
    diamondExchangeRate: "100 ماس = 0.01 زهور",
    cryptoWithdrawPage: "سحب العملات المشفرة",
    ticketsAvailable: "التذاكر المتاحة",
    spinning: "جارٍ الدوران...",
    noTickets: "لا توجد تذاكر",
    spinWheel: "أدر العجلة",
    youWon: "🎉 لقد فزت! 🎉",
    howToGetTickets: "كيفية الحصول على التذاكر؟",
    buyFlowersTicketInfo:
      "اشترِ الزهور في المتجر! كل عملية شراء بقيمة 10 دولارات تمنحك تذكرة واحدة.",
    exchangePage: "التبادل",
    yourBalances: "أرصدتك",
    exchangeType: "نوع التبادل",
    diamondsToFlowers: "الماس إلى الزهور",
    bvrToFlowers: "BVR إلى الزهور",
    amountToExchange: "المبلغ المراد تبادله",
    exchangePreview: "معاينة التبادل",
    youGive: "أنت تعطي",
    bonus: "مكافأة",
    noFees: "لا توجد رسوم",
    instant: "التبادل فوري",
    walletPage: "المحفظة",
    receiveAddresses: "عناوين الاستلام",
    sendCryptoInfo: "أرسل العملات المشفرة إلى هذه العناوين لتلقي الزهور",
    address: "العنوان",
    exchangeCrypto: "تبادل العملات المشفرة",
    afterSendingConfirm: "بعد إرسال العملات المشفرة، أكد التبادل هنا",
    networkLabel: "الشبكة",
    amountSent: "المبلغ المرسل",
    youWillReceiveFlowers: "سوف تستلم",
    minimum: "الحد الأدنى",
    confirmExchange: "تأكيد التبادل",
    important: "مهم",
    verifyAddressWarning: "تحقق من العنوان قبل الإرسال",
    cryptoIrreversible: "معاملات العملات المشفرة لا رجعة فيها",
    useCorrectNetwork: "استخدم الشبكة الصحيحة (Solana أو TON)",
    minAmountWarning: "الحد الأدنى للمبلغ: 5 دولارات (40,000 زهرة)",
    exchangeAfterReceipt: "يحدث التبادل بعد استلام معاملتك",
    exchangeQuestion: "تبادل {amount} {currency} مقابل {flowers} زهرة؟",
    received: "لقد استلمت {flowers} زهرة!",
    copied2: "تم نسخ العنوان إلى الحافظة",
    invalidAmount: "مبلغ غير صالح",
    selectNetworkError: "الرجاء تحديد شبكة",
    selectExchangeType: "الرجاء تحديد نوع التبادل",
    minBVRError: "الحد الأدنى للمبلغ هو 100 BVR للحصول على 0.01 زهرة",
    onSolana: "على Solana",
    networkOnlyForBVR: "الشبكة الوحيدة لسحب BVR",
    minimum2: "الحد الأدنى",
    fillAllFields: "الرجاء ملء جميع الحقول",
    passwordsDontMatch: "كلمات المرور غير متطابقة",
    passwordTooShort: "يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل",
    createAccount: "إنشاء حساب",
    login: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    enterEmail: "أدخل بريدك الإلكتروني",
    password: "كلمة المرور",
    enterPassword: "أدخل كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    confirmPasswordPlaceholder: "أكد كلمة المرور",
    sponsorCode: "رمز الراعي (اختياري)",
    enterSponsorCode: "أدخل رمز الراعي",
    register: "تسجيل",
    loginButton: "تسجيل الدخول",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟ سجل الدخول",
    dontHaveAccount: "ليس لديك حساب؟ سجل",
    leaderboard: "لوحة المتصدرين",
    diamondLeaderboard: "لوحة متصدري الماس",
    topProducers: "أفضل المنتجين السنويين",
    you: "أنت",
    joinBeeMinorPlayWin: "انضم إلى BeeMinor، العب واربح",
    forgotPassword: "نسيت كلمة المرور؟",
    sendCode: "إرسال الرمز",
    resetPasswordTitle: "إعادة تعيين كلمة المرور",
    resetButton: "إعادة تعيين",
    resetCode: "رمز إعادة التعيين",
    enterResetCode: "أدخل الرمز المستلم عبر البريد الإلكتروني",
    newPassword: "كلمة مرور جديدة",
    enterNewPassword: "أدخل كلمة مرورك الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    confirmYourNewPassword: "أكد كلمة مرورك الجديدة",
    backToLogin: "العودة إلى تسجيل الدخول",
    emailSent: "تم إرسال البريد الإلكتروني",
    resetCodeSentTo: "تم إرسال رمز إعادة التعيين إلى",
    checkLogsForCode: "تحقق من السجلات الخاصة بك للحصول على رمز الاختبار:",
    passwordResetSuccess:
      "تمت إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول.",
    canNowLogin: "يمكنك الآن تسجيل الدخول",
    winChances: "فرص الفوز",
    claimFailed: "فشل الاستحقاق",
  },
  id: {
    home: "Beranda",
    shop: "Toko",
    hive: "Sarang",
    alveole: "Sel",
    menu: "Menu",
    tasks: "Tugas",
    honey: "Madu",
    flowers: "Bunga",
    diamonds: "Berlian",
    bees: "Lebah",
    honeyPerHour: "Madu/Jam",
    honeyPerSec: "Madu/Detik",
    faq: "FAQ",
    help: "Bantuan",
    accountDetails: "Detail Akun",
    transactionHistory: "Riwayat",
    loading: "Memuat...",
    babyBee: "Lebah Bayi",
    workerBee: "Lebah Pekerja",
    eliteBee: "Lebah Elite",
    royalBee: "Lebah Kerajaan",
    queenBee: "Ratu Lebah",
    buy: "Beli",
    exchange: "Tukar",
    withdraw: "Tarik",
    roulette: "Roulette",
    wallet: "Dompet",
    missions: "Misi",
    invite: "Undang",
    referrals: "Rujukan",
    myReferralCode: "Kode rujukan saya",
    inviteLink: "Tautan undangan",
    friendsInvited: "Teman yang diundang",
    totalEarnings: "Total pendapatan",
    myResources: "Sumber Daya Saya",
    buyFlowers: "Beli Bunga",
    smallPack: "Paket Kecil",
    mediumPack: "Paket Sedang",
    largePack: "Paket Besar",
    giantPack: "Paket Raksasa",
    owned: "Dimiliki",
    statistics: "Statistik Produksi",
    totalProduction: "Produksi total",
    totalBees: "Jumlah total lebah",
    maxCapacity: "Kapasitas maksimum",
    close: "Tutup",
    chooseLanguage: "Pilih bahasa",
    spinTheWheel: "Putar roda untuk memenangkan hadiah",
    withdrawCrypto: "Tarik berlian Anda dalam crypto",
    exchangeResources: "Tukar sumber daya Anda dengan bunga",
    receiveAndExchange: "Terima crypto dan tukar dengan bunga",
    selectNetwork: "Pilih jaringan",
    walletAddress: "Alamat dompet",
    withdrawAmount: "Jumlah penarikan",
    summary: "Ringkasan",
    amount: "Jumlah",
    fees: "Biaya",
    youWillReceive: "Anda akan menerima",
    importantInfo: "Informasi penting",
    error: "Kesalahan",
    success: "Berhasil",
    confirmation: "Konfirmasi",
    cancel: "Batal",
    confirm: "Konfirmasi",
    enterWalletAddress: "Silakan masukkan alamat dompet",
    enterValidAmount: "Silakan masukkan jumlah yang valid",
    notEnoughDiamonds: "Anda tidak memiliki cukup berlian",
    notEnoughBVR: "Anda tidak memiliki cukup BVR",
    withdrawalSubmitted:
      "Permintaan penarikan Anda telah dikirim. Anda akan menerima dana dalam 24-48 jam.",
    bvrWithdrawalSubmitted:
      "Permintaan penarikan BVR Anda telah dikirim. Anda akan menerima dana di Solana dalam 24-48 jam.",
    availableBalance: "Saldo tersedia",
    network: "Jaringan",
    minimumWithdraw: "Min",
    conversionRate: "Nilai tukar",
    processingTime: "Waktu pemrosesan",
    verifyAddress: "Silakan verifikasi alamat Anda sebelum konfirmasi",
    coldWalletRequired: "PERHATIAN - Dompet Dingin Diperlukan",
    inviteFriendBonus: "Undang teman",
    copyReferralCode: "Disalin!",
    copyInviteLink: "Salin tautan undangan",
    copied: "Kode rujukan disalin ke clipboard",
    alreadyClaimed: "Anda sudah mengklaim hadiah ini",
    missionIncomplete: "Misi belum selesai",
    rewardClaimed: "Hadiah diklaim!",
    referralBonus: "Bonus rujukan",
    perFriend: "per teman yang diundang",
    firstPurchaseBonus: "jika rujukan Anda melakukan pembelian pertama",
    firstDepositPercent: "dari jumlah deposit pertama",
    lifetimePercent: "seumur hidup untuk semua deposit berikutnya",
    inviteFriends: "Undang",
    progress: "Kemajuan",
    claim: "Klaim",
    claimed: "Diklaim",
    inProgress: "Sedang berlangsung",
    noReferrals: "Belum ada rujukan",
    inviteToEarn: "Undang teman Anda untuk mulai mendapatkan hadiah!",
    joinedOn: "Bergabung pada",
    totalDeposits: "Total deposit",
    firstDeposit: "Deposit pertama",
    lifetimeEarnings: "Pendapatan seumur hidup",
    bvr: "BVR",
    cryptoWithdraw: "Tarik Crypto",
    account: "Akun",
    history: "Riwayat",
    sellHoney: "Jual madu",
    honeyExchange: "Tukar madu",
    honeyExchangeRate: "1 miel (USDT) = 1 💎 berlian",
    quickSell: "Jual cepat",
    sellAllHoney: "Jual semua madu",
    alveoleLevels: "Level Sel",
    level: "Level",
    unlocked: "✓ Terbuka",
    capacity: "Kapasitas",
    cost: "Biaya",
    unlock: "Buka",
    currentLevel: "Level saat ini",
    alveoleUnlocked: "Sel level {level} terbuka!",
    insufficientFlowers: "Bunga tidak cukup",
    needFlowers: "Anda membutuhkan {amount} bunga.",
    insufficientHoney: "Madu tidak cukup",
    needMinHoney: "Anda membutuhkan setidaknya 100 madu untuk dijual.",
    sold: "Terjual!",
    transactionSuccess: "Transaksi berhasil!",
    transactionFailed: "Transaksi gagal",
    diamondExchangeRate: "100 berlian = 0.01 bunga",
    cryptoWithdrawPage: "Tarik Crypto",
    ticketsAvailable: "Tiket tersedia",
    spinning: "Berputar...",
    noTickets: "Tidak ada tiket",
    spinWheel: "PUTAR RODA",
    youWon: "🎉 Anda menang! 🎉",
    howToGetTickets: "Bagaimana cara mendapatkan tiket?",
    buyFlowersTicketInfo:
      "Beli bunga di toko! Setiap pembelian $10 memberi Anda 1 tiket.",
    exchangePage: "Tukar",
    yourBalances: "Saldo Anda",
    exchangeType: "Jenis tukar",
    diamondsToFlowers: "Berlian ke Bunga",
    bvrToFlowers: "BVR ke Bunga",
    amountToExchange: "Jumlah untuk ditukar",
    exchangePreview: "Pratinjau tukar",
    youGive: "Anda berikan",
    bonus: "Bonus",
    noFees: "Tanpa biaya",
    instant: "Tukar instan",
    walletPage: "Dompet",
    receiveAddresses: "Alamat penerima",
    sendCryptoInfo: "Kirim crypto ke alamat ini untuk menerima bunga",
    address: "Alamat",
    exchangeCrypto: "Tukar crypto",
    afterSendingConfirm:
      "Setelah mengirim crypto, konfirmasi penukaran di sini",
    networkLabel: "Jaringan",
    amountSent: "Jumlah yang dikirim",
    youWillReceiveFlowers: "Anda akan menerima",
    minimum: "Minimum",
    confirmExchange: "Konfirmasi tukar",
    important: "Penting",
    verifyAddressWarning: "Verifikasi alamat sebelum mengirim",
    cryptoIrreversible: "Transaksi crypto tidak dapat dibatalkan",
    useCorrectNetwork: "Gunakan jaringan yang benar (Solana atau TON)",
    minAmountWarning: "Jumlah minimum: $5 (40.000 bunga)",
    exchangeAfterReceipt: "Penukaran terjadi setelah menerima transaksi Anda",
    exchangeQuestion: "Tukar {amount} {currency} untuk {flowers} bunga?",
    received: "Anda menerima {flowers} bunga!",
    copied2: "Alamat disalin ke clipboard",
    invalidAmount: "Jumlah tidak valid",
    selectNetworkError: "Silakan pilih jaringan",
    selectExchangeType: "Silakan pilih jenis tukar",
    minBVRError: "Jumlah minimum adalah 100 BVR untuk mendapatkan 0.01 bunga",
    onSolana: "di Solana",
    networkOnlyForBVR: "Satu-satunya jaringan untuk penarikan BVR",
    minimum2: "Min",
    fillAllFields: "Silakan isi semua bidang",
    passwordsDontMatch: "Kata sandi tidak cocok",
    passwordTooShort: "Kata sandi harus minimal 6 karakter",
    createAccount: "Buat Akun",
    login: "Masuk",
    email: "Email",
    enterEmail: "Masukkan email Anda",
    password: "Kata Sandi",
    enterPassword: "Masukkan kata sandi Anda",
    confirmPassword: "Konfirmasi Kata Sandi",
    confirmPasswordPlaceholder: "Konfirmasi kata sandi Anda",
    sponsorCode: "Kode sponsor (opsional)",
    enterSponsorCode: "Masukkan kode sponsor",
    register: "Daftar",
    loginButton: "Masuk",
    alreadyHaveAccount: "Sudah punya akun? Masuk",
    dontHaveAccount: "Belum punya akun? Daftar",
    leaderboard: "Papan Peringkat",
    diamondLeaderboard: "Papan Peringkat Berlian",
    topProducers: "Produser Tahunan Teratas",
    you: "Anda",
    joinBeeMinorPlayWin: "Bergabunglah dengan BeeMinor, mainkan dan menangkan",
    forgotPassword: "Lupa kata sandi?",
    sendCode: "Kirim kode",
    resetPasswordTitle: "Atur ulang kata sandi",
    resetButton: "Atur ulang",
    resetCode: "Kode reset",
    enterResetCode: "Masukkan kode yang diterima melalui email",
    newPassword: "Kata sandi baru",
    enterNewPassword: "Masukkan kata sandi baru Anda",
    confirmNewPassword: "Konfirmasi kata sandi baru",
    confirmYourNewPassword: "Konfirmasi kata sandi baru Anda",
    backToLogin: "Kembali ke login",
    emailSent: "Email terkirim",
    resetCodeSentTo: "Kode reset telah dikirim ke",
    checkLogsForCode: "Periksa log Anda untuk kode tes:",
    passwordResetSuccess:
      "Kata sandi Anda telah berhasil diatur ulang. Anda sekarang dapat masuk.",
    canNowLogin: "Anda sekarang dapat masuk",
    winChances: "Peluang Menang",
    claimFailed: "Klaim gagal",
  },
};

const STORAGE_KEY = "app_language";

export const [LanguageProvider, useLanguage] = createContextHook(() => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>("fr");
  const [isLoaded, setIsLoaded] = useState<boolean>(false);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const stored = await AsyncStorage.getItem(STORAGE_KEY);
      if (stored && translations[stored as Language]) {
        setCurrentLanguage(stored as Language);
      }
    } catch (error) {
      console.error("Failed to load language:", error);
    } finally {
      setIsLoaded(true);
    }
  };

  const changeLanguage = useCallback(async (lang: Language) => {
    try {
      await AsyncStorage.setItem(STORAGE_KEY, lang);
      setCurrentLanguage(lang);
    } catch (error) {
      console.error("Failed to save language:", error);
    }
  }, []);

  const t = useMemo(() => translations[currentLanguage], [currentLanguage]);

  return useMemo(
    () => ({
      currentLanguage,
      changeLanguage,
      t,
      isLoaded,
    }),
    [currentLanguage, changeLanguage, t, isLoaded]
  );
});
